name: "grafana"
include:
    - ../compositions/shared/docker-compose.network.yml
services:
  alloy:
    image: grafana/alloy:latest
    networks:
      - embroker
    ports:
      - "12345:12345"
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: >
      run 
      --server.http.listen-addr=0.0.0.0:12345 
      --storage.path=/var/lib/alloy/data 
      --stability.level=experimental
      /etc/alloy/config.alloy
    profiles:
      - remote
      - local

  loki:
    image: grafana/loki:latest
    networks:
      - embroker
    user: "0:0"
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki.yml:/etc/loki/local-config.yaml
      - loki-data:/tmp/loki
    command: -config.file=/etc/loki/local-config.yaml
    profiles:
      - local

  node-exporter:
    image: prom/node-exporter:latest
    networks:
      - embroker
    container_name: node-exporter
    restart: unless-stopped
    labels:
      prometheus.scrape: "true"
      prometheus.port: "9090"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    profiles:
      - local

  tempo:
    image: grafana/tempo:2.4.1
    networks:
      - embroker
    command: [ "-target=all", "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    ports:
      - "3200:3200"   # HTTP API / Ring
    profiles:
      - local

  prometheus:
    image: prom/prometheus:latest
    networks:
      - embroker
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-remote-write-receiver'
    profiles:
      - local

  grafana:
    image: grafana/grafana:latest
    networks:
      - embroker
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    profiles:
      - local

volumes:
  loki-data:
  grafana-storage:
  prometheus-data:
  tempo-data:
